#数据库驱动mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#日志打印
logging:
  level:
    root: info
    com.tjy.myblog: debug
  file: log/Blog-dev.log
server:
  port: 8080